name: sei4.1.5-precarga-sqlserver

on:
  push:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/testCargaPre.yml
    secrets: inherit
    with:
      sei-version: 4.1.5
      db: sqlserver
