name: sei4.0.12-precarga-postgres

on:
  push:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/testCargaPre.yml
    secrets: inherit
    with:
      sei-version: 4.0.12
      db: postgres

