name: Matrix Run

on:
  workflow_dispatch:
    inputs:
        sei-version:
            required: true
            type: string
  workflow_call:
    inputs:
        sei-version:
            required: true
            type: string

jobs:

  temp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sei-version: [4.0.9, 4.1.5]

    uses: ./.github/workflows/badges/testPreVersao.yml
    secrets: inherit
    with:
      sei-version: ${{ matrix.sei-version }}
