name: Main CI pipeline

on:
  workflow_dispatch:

jobs:
  trigger-reusable-matrix:
    strategy:
      matrix:
        sei-version: ["4.1.5"]

    # Call the reusable workflow
    uses: ./.github/workflows/test415.yml
    secrets: inherit
    with:
      sei-version: ${{ matrix.sei-version }}
